# Generated by Django 5.2.5 on 2025-09-01 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher', models.CharField(max_length=70)),
                ('content', models.TextField()),
                ('publish_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
