# Generated by Django 5.2.5 on 2025-09-01 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='comment',
        ),
    ]
