# Generated by Django 5.2.5 on 2025-09-01 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_rename_body_comment_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='body',
        ),
    ]
