# Generated by Django 5.2.5 on 2025-09-16 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0008_remove_comment_created_at_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='article/image/'),
        ),
        migrations.AddField(
            model_name='article',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='article/video/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default='Untitled', max_length=255),
        ),
    ]
